/*
THIS FILE IS AUTOMATICALLY CREATED BY CMAKE AND FETCHES THE LATEST VERSION FROM GIT!
DO NOT MODIFY!
*/

#ifndef CONFIG_H
#define CONFIG_H

#define YOSHIKO_VERSION "ds/dev-3b91123"

#endif // CONFIG_H
